"""
ui/app.py

Streamlit dashboard for the Multi-Agent Finance Advisor.

Data source: imports query functions from agents/storage_agent.py directly.
No HTTP API needed — Streamlit runs in the same codebase.

To run locally:  streamlit run ui/app.py
In Docker:       separate service in docker-compose.yml (port 8501)
"""

import os
import sys

import streamlit as st

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from agents.storage_agent import get_latest_prices, get_recent_headlines, get_recent_insights

st.set_page_config(
    page_title="AI Finance Advisor",
    page_icon="📈",
    layout="wide",
)

st.title("📈 Multi-Agent AI Finance Advisor")
st.caption(
    "Powered by Google Gemini 1.5 Flash (free tier) · "
    "Data: Yahoo Finance + RSS feeds · "
    "All open-source, zero cost"
)

st.header("Current Market Prices")
prices = get_latest_prices()

if prices:
    cols = st.columns(min(len(prices), 5))
    for col, item in zip(cols, prices):
        col.metric(label=item["symbol"], value=f"${item['price']:,.2f}")
    st.caption(f"Last updated: {prices[0]['captured_at']}")
else:
    st.info("⏳ Waiting for first data fetch (up to 5 minutes)...")

st.header("Recent News Headlines")
headlines = get_recent_headlines(limit=10)

if headlines:
    for h in headlines:
        url = h.get("url", "")
        headline_text = h["headline"]
        if url:
            st.markdown(f"- [{headline_text[:120]}]({url}) — *{h['source']}*")
        else:
            st.markdown(f"- {headline_text[:120]} — *{h['source']}*")
else:
    st.info("⏳ No headlines yet...")

st.header("AI-Generated Insights")
st.caption("Generated by Gemini 1.5 Flash · Refreshes every 10 minutes")

insights = get_recent_insights(limit=5)

if insights:
    for insight in insights:
        with st.expander(
            f"🤖 {insight['generated_at'][:16]}  —  {insight['sentiment_summary']}",
            expanded=(insight == insights[0]),
        ):
            st.write(insight["insight_text"])

            if insight["sources"]:
                valid_sources = [s for s in insight["sources"] if s]
                if valid_sources:
                    st.caption("Sources: " + " · ".join(valid_sources[:3]))

            st.caption(f"Model: {insight['model_used']}")
else:
    st.info(
        "⏳ No insights yet. The analysis agent runs every 10 minutes. "
        "Check back shortly or reduce ANALYSIS_INTERVAL_SECONDS in .env for faster testing."
    )

st.divider()
col1, col2 = st.columns([3, 1])
col1.caption("This is a personal project for educational purposes. Not financial advice.")
if col2.button("🔄 Refresh"):
    st.rerun()
